TFG_PATH = "/content/drive/MyDrive/TFG/"
TFG_METADATA_ORIGINAL = TFG_PATH + "train.csv"
TFG_METADATA_ITA = TFG_PATH + "TFG_tono_piel_ITA.csv"
TFG_METADATA = TFG_PATH + "TFG_metadatos.csv"
TFG_PREDICCIONES = TFG_PATH + "TFG_mejor_modelo_pred.csv"
TFG_MODEL_AWS = TFG_PATH + "TFG_mejor_modelo.tar.gz"